services:

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8085:8080"
      - "7077:7077"
    networks:
      - pipeline-net

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: "2"
    depends_on:
      - spark-master
    networks:
      - pipeline-net

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pipeline-net

  airflow:
    build: .
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      POSTGRES_HOST: postgres-db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: ecommerce_db
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./sql:/opt/airflow/sql
    command: standalone
    depends_on:
      - postgres-db
    networks:
      - pipeline-net
# ── Grafana ───────────────────────────────────────
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - pipeline-net

volumes:
  postgres_data:

networks:
  pipeline-net:
    driver: bridge